name: First Workflow
on:
       workflow_dispatch:
jobs:
     greet:
                 runs-on: windows-latest
                    steps:
                        name: Print greeting
                        run: echo "Hello-World"
        
     
     
    
    
  
